trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      arguments: --configuration Release
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: --configuration Release